#UNA FUNCION PUEDE ACEPTAR DIVERSOS PARAMETROS, PERO PUEDE SUCEDER QUE NECESITEMOS MAS DE UNA LLAMADA A LA FUNCION O METODO.
#EN ESTE CASO ES UTIL AGREGAR VARIOS PARAMETROS A LA VEZ, PERO EN LA MISMA FUNCION, DE MODO QUE EL METODO TRABAJE CON ELLOS DE FORMA INDEPENDIENTE.

#A ESTO SE LE LLAMA PARAMETROS ARBITRARIOS.

#PARA ELLO LO QUE HAREMOS ES AGREGAR * AL PARAMETRO

#SINTAXIS DE UNA FUNCION QUE ACEPTAR VARIOS PARAMETROS Y QUE TRABAJA CON CADA UNO DE ELLOS: 

# def nombreFuncion (*parametro):

def agregar_toppings_pizza(*toppings):

    for topping in toppings:

        print ("Agregando: -" + topping)

#VAMOS A AGREGAR DE GOLPE VARIOS TOPPINGS A LA PIZZA

agregar_toppings_pizza('peperoni', 'champinones', 'salsa especial de tomate', 'orilla rellena de queso')#AGREGO HASTA 4 PARAMETROS DIFERENTES

#A CADA PARAMETRO SE LE HACE LO DE LA FUNCION.  